apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
  labels:
    app: demoapp-deployment
    env: dev
spec:
  template:
    metadata: 
      name: demoapp-pod
      labels:
        app: demoapp-deployment
        env: dev
        type: frontend
    spec:
      containers:
      - name: demoapp-container
        image: nginx:latest
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
  replicas: 3
  selector:
    matchLabels:      
      env: dev
      